// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApp.Data.Concrete;

#nullable disable

namespace StoreApp.Web.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("StoreApp.Data.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Category#1",
                            Description = "Product#1Description",
                            Name = "Product#1",
                            Price = 9999m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Category#2",
                            Description = "Product#2Description",
                            Name = "Product#2",
                            Price = 9999m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Category#3",
                            Description = "Product#3Description",
                            Name = "Product#3",
                            Price = 9999m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Category#4",
                            Description = "Product#4Description",
                            Name = "Product#4",
                            Price = 9999m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Category#5",
                            Description = "Product#5Description",
                            Name = "Product#5",
                            Price = 9999m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Category#6",
                            Description = "Product#6Description",
                            Name = "Product#6",
                            Price = 9999m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
